threads: 20
memory: 250000
jobs: 1
model: "r1041_e82_400bps_sup_v5.0.0"

tools:
  Seqkit:
    path: "/usr/local/bin/lmod/seqkit/2.3.1/"
  Samtools:
    path: "/usr/local/bin/lmod/samtools/1.17/bin/"
  KMA:
    path: "/usr/local/bin/lmod/kma/1.4.15/"
    resfinder_db: "/db/resfinder4/latest/all"
    taxonomic_db: "/scratch/alvanuffelen/kma_v2/kma_db"
  Kraken2:
    path: "/usr/local/bin/lmod/kraken2_remote/2.1.1/venv/bin"
    db: "/db/kraken2_full/20240113/"
  Krona:
    path: "/usr/local/bin/lmod/krona/2.8.1/bin/"
  Flye:
    path: "/usr/local/bin/lmod/flye/2.9.4/bin/"
  minimap2:
    path: "/usr/local/bin/lmod/minimap2/2.28/"
  Medaka:
    htslib_path: "/usr/local/bin/lmod/htslib/1.21"
    path: "/usr/local/bin/lmod/medaka/2.0.0/venv/bin"
  Metabat:
    path: "/usr/local/bin/lmod/metabat2/2.15"
    bin_path: "/usr/local/bin/lmod/metabat2/2.15/bin"
  CheckM:
    path: "/usr/local/bin/lmod/CheckM/1.2.2/venv/bin"
    dependencies: ":/usr/local/bin/lmod/pplacer/1.1.alpha19:/usr/local/bin/lmod/prodigal/2.6.3:/usr/local/bin/lmod/hmmer/3.4/bin"
  GTDBtk:
    path: "/usr/local/bin/lmod/gtdb-tk/2.3.2/venv/bin"
    dependencies: "/usr/local/bin/lmod/fasttree/2.1.11:/usr/local/bin/lmod/fastani/1.33:/usr/local/bin/lmod/gtdb-tk/2.3.2:/usr/local/bin/lmod/pplacer/1.1.alpha19:/usr/local/bin/lmod/prodigal/2.6.3:/usr/local/bin/lmod/hmmer/3.4/bin"